### ISSUE TITLE
Count method broken on complex queries

### ISSUE THREAD

**Issue by nickfrandsen** [rails-sqlserver/activerecord-sqlserver-adapter#613] opened 2017-08-08 05:12 UTC
I think there is an issue with the count method on a complex query as `@filtered_skew_panels[agglo_code].map(&:panel_id).count` be does not equal `@filtered_skew_panels[agglo_code].count`?

    ActiveRecord::Base.connection.query_cache.clear
    # => {}
    Panel.connection.schema_cache.clear!
    # => nil
    Panel.reset_column_information
    # => nil
    @filtered_skew_panels[agglo_code].map(&:panel_id).count
    # => 57
    @filtered_skew_panels[agglo_code].all.count
      (13.1ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "panels" WHERE "panels"."agglo_code_id" = $1 AND "panels"."environment_id" = $2 AND "panels"."product_id" = $3 AND "panels"."alcohol_friendly" = $4 AND "panels"."suburb" = 'Marrickville' AND (NOT EXISTS(SELECT 1 FROM campaign_search_panels WHERE campaign_search_panels.panel_id = panels.panel_id AND campaign_search_panels.campaign_id = 52)) AND (NOT EXISTS(SELECT 1 FROM "AIDAAU_Avails" WHERE "AIDAAU_Avails"."PanelID" = panels.panel_uid AND "AIDAAU_Avails"."TillDate" >= '2017-08-21 00:00:00.000000' AND "AIDAAU_Avails"."FromDate" <= '2017-09-03 00:00:00.000000')) LIMIT 100) subquery_for_count  [["agglo_code_id", 4], ["environment_id", 2], ["product_id", 1], ["alcohol_friendly", "t"]]
    # => 0

The relation itself seems to actually contain all the records:

    [3] pry(#<PanelSearch>)> @filtered_skew_panels[agglo_code]
    => [#<Panel:0x007fe4ef779990
      location_type: "Street",
      move_id: "27779",
      panel_id: "11441A1",
      address: "Victoria Rd N/O Sydenham Rd E/S",
      postal_code: "2204",
      suburb: "Marrickville",
      latitude: #<BigDecimal:7fe4ee0b14b0,'-0.33909329E2',18(27

    [5] pry(#<PanelSearch>)> @filtered_skew_panels[agglo_code].class
    => Panel::ActiveRecord_Relation

    [6] pry(#<PanelSearch>)> @filtered_skew_panels[agglo_code].to_sql
    => "SELECT  \"panels\".* FROM \"panels\" WHERE \"panels\".\"agglo_code_id\" = 4 AND \"panels\".\"environment_id\" = 2 AND \"panels\".\"product_id\" = 1 AND \"panels\".\"alcohol_friendly\" = 't' AND \"panels\".\"suburb\" = 'Marrickville' AND (NOT EXISTS(SELECT 1 FROM campaign_search_panels WHERE campaign_search_panels.panel_id = panels.panel_id AND campaign_search_panels.campaign_id = 52)) AND (NOT EXISTS(SELECT 1 FROM \"AIDAAU_Avails\" WHERE \"AIDAAU_Avails\".\"PanelID\" = panels.panel_uid AND \"AIDAAU_Avails\".\"TillDate\" >= '2017-08-21 00:00:00.000000' AND \"AIDAAU_Avails\".\"FromDate\" <= '2017-09-03 00:00:00.000000')) LIMIT 500"
    [7] pry(#<PanelSearch>)> @filtered_skew_panels[agglo_code].all.to_sql
    => "SELECT  \"panels\".* FROM \"panels\" WHERE \"panels\".\"agglo_code_id\" = 4 AND \"panels\".\"environment_id\" = 2 AND \"panels\".\"product_id\" = 1 AND \"panels\".\"alcohol_friendly\" = 't' AND \"panels\".\"suburb\" = 'Marrickville' AND (NOT EXISTS(SELECT 1 FROM campaign_search_panels WHERE campaign_search_panels.panel_id = panels.panel_id AND campaign_search_panels.campaign_id = 52)) AND (NOT EXISTS(SELECT 1 FROM \"AIDAAU_Avails\" WHERE \"AIDAAU_Avails\".\"PanelID\" = panels.panel_uid AND \"AIDAAU_Avails\".\"TillDate\" >= '2017-08-21 00:00:00.000000' AND \"AIDAAU_Avails\".\"FromDate\" <= '2017-09-03 00:00:00.000000')) LIMIT 500"

**Comment by metaskills** [comment] 2017-09-06 02:22
Thanks. Could you provide a simple test case that breaks this down to the most simple example? Please use #616 how to reproduce as an example. As is now, we are passing tests in ActiveRecord which I assumed tests this too. Maybe track one of those down to help with the test case. Example, I see in our coerced tests we have a `test_count_with_include` which is only coerced because we use `LEN()` function.

**Comment by metaskills** [comment] 2017-09-22 03:22
Hmm... seems this is broken in master. Maybe a recent Rails core change. Will look into it.

**Comment by metaskills** [comment] 2017-09-22 03:29
Hmm... seems related to this. https://github.com/rails/rails/pull/29848

**Comment by metaskills** [comment] 2017-09-23 01:45
Pull request to Rails here https://github.com/rails/rails/pull/30686 but we will have to do some form of monkey patch to ensure Rails v5.1.4 works for us in the meantime.

**Comment by metaskills** [comment] 2017-09-23 02:16
This fix will be in our v5.1.3 release in a day or two.

**Closed** 2017-09-23 02:16 UTC
Labels: Bug
