### ISSUE TITLE
SQL Server 2014 support

### ISSUE THREAD

**Issue by chrisgogreen** [rails-sqlserver/activerecord-sqlserver-adapter#398] opened 2015-03-28 19:29 UTC
when connecting to 2014, i get 

```
NotImplementedError (Currently, only 2005, 2008, 2010, 2011, and 2012 are supported. We got back Microsoft SQL Server 2014 - 12.0.2000.8 (X64) 
	Feb 20 2014 20:04:26 
	Copyright (c) Microsoft Corporation
	Enterprise Edition: Core-based Licensing (64-bit) on Windows NT 6.3 <X64> (Build 9600: )

```

Wiki says supports 2012 and higher.

**Comment by metaskills** [comment] 2015-03-28 20:11
This sound like you are on an outdated version of the adapter? What version of Rails and the Adapter are you using?

**Comment by metaskills** [comment] 2015-04-05 14:24
Closing since the issue is that you have to use the latest version of the the adapter.

**Closed by metaskills** 2015-04-05 14:24 UTC
