### ISSUE TITLE
Unable to run tests due to network timeout

### ISSUE THREAD

**Issue by gisborne** [rails-sqlserver/activerecord-sqlserver-adapter#927] opened 2021-05-21 19:40 UTC
## Issue
Clone repo and bundle exec rake fails due to network timeout loading Gemfile while fetching "/api/v1/versions/activerecord.yaml"

## Expected behavior
Tests should run

## Actual behavior
```
% cd /tmp
% git clone https://github.com/rails-sqlserver/activerecord-sqlserver-adapter.git
Cloning into 'activerecord-sqlserver-adapter'...
remote: Enumerating objects: 14111, done.
remote: Counting objects: 100% (514/514), done.
remote: Compressing objects: 100% (243/243), done.
remote: Total 14111 (delta 299), reused 448 (delta 252), pack-reused 13597
Receiving objects: 100% (14111/14111), 3.26 MiB | 2.77 MiB/s, done.
Resolving deltas: 100% (7370/7370), done.
% cd activerecord-sqlserver-adapter 
% bundle exec rake

[!] There was an error parsing `Gemfile`: execution expired. Bundler cannot continue.

 #  from /private/tmp/activerecord-sqlserver-adapter/Gemfile:34
 #  -------------------------------------------
 #        http.verify_mode = OpenSSL::SSL::VERIFY_NONE
 >        YAML.load(http.request(Net::HTTP::Get.new(uri.request_uri)).body).find do |data|
 #          a, b, = data["number"].split(".")
 #  -------------------------------------------
```

## How to reproduce
See above

## Details

- **Rails version**: Test version included with Gem (6.1.3.2)
- **SQL Server adapter version**: 6.1.3.2
- **TinyTDS version**: 2.1.3
- **FreeTDS details**: 1.2.20

  ```
  run `tsql -C` and paste here the output.
  ```

Compile-time settings (established with the "configure" script)
                            Version: freetds v1.2.20
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: yes

**Comment by aidanharan** [comment] 2021-07-13 08:21
Unable to reproduce the issue. 

If it's still happening could you provide the commit you are on using `git rev-parse HEAD`? Also, have you tried using the ActiveRecord SQL Server Adapter Development (https://github.com/rails-sqlserver/activerecord-sqlserver-adapter-dev-box) instead of your local environment to run the tests?

**Comment by wpolicarpo** [comment] 2021-07-29 12:42
I don't believe the issue is on our side, but some connectivity issue between you and rubygems.

Please, make sure you can reach https://rubygems.org/api/v1/versions/activerecord.yaml for example where you are trying to run the test from.

I'm closing this off for now.

**Closed by wpolicarpo** 2021-07-29 12:42 UTC
