### ISSUE TITLE
Crash when using Rails console to list records

### ISSUE THREAD

**Issue by shrmnk** [rails-sqlserver/activerecord-sqlserver-adapter#680] opened 2019-02-22 11:18 UTC
### Environment
macOS 10.14.3
Ruby 2.5.3 (with rvm)
Rails 5.2.2

### Relevant lines in Gemfile
```
gem 'tiny_tds'
gem 'activerecord-sqlserver-adapter', '= 5.2.0.rc1'
```

---

### Description

```shell
> rails c
Running via Spring preloader in process 25900
Loading development environment (Rails 5.2.2)
[1] pry(main)> Member.first
objc[25900]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[25900]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Same thing happens when doing `Member.all`.

This is a brand new rails 5 API app, created using `rails new -T --database=sqlserver --api`, with a few added models and relations which passed appropriate tests (rspec).

**Comment by wpolicarpo** [comment] 2019-02-22 11:35
This is probably not an issue with the gem or Rails itself as seen [here](https://blog.phusion.nl/2017/10/13/why-ruby-app-servers-break-on-macos-high-sierra-and-what-can-be-done-about-it/).

Can you show us the output of both `tsql -C` and `xcode-select -v`?

How did you install `freetds`?

**Comment by shrmnk** [comment] 2019-02-22 14:24
```shell
> tsql -C
Compile-time settings (established with the "configure" script)
                            Version: freetds v1.00.109
             freetds.conf directory: /usr/local/etc
     MS db-lib source compatibility: no
        Sybase binary compatibility: yes
                      Thread safety: yes
                      iconv library: yes
                        TDS version: 7.3
                              iODBC: no
                           unixodbc: yes
              SSPI "trusted" logins: no
                           Kerberos: yes
                            OpenSSL: yes
                             GnuTLS: no
                               MARS: no
> xcode-select -v
xcode-select version 2354.
```

Appreciate your help even though it doesn't appear to be this gem.

freetds was installed via homebrew.

I've never encountered this before using freetds and this gem. I have an identical application with the exact same models, but using Postgres as the database and this error doesn't happen, so I naturally thought it was due to the change to sqlserver.

**Comment by wpolicarpo** [comment] 2019-02-22 14:35
How about `openssl version`?

This might be coming from `freetds`/`tiny_tds`, but it's probably related to your environment as explained on that post above.

I have exactly the same versions as you and I can't see any issues.

**Comment by wpolicarpo** [comment] 2019-06-22 22:32
@shrmnk is this still a problem? Did you manage to make it work?

**Comment by etcook** [comment] 2019-08-02 13:57
@wpolicarpo I'm running into this issue as well, although I have a slightly different setup.

macOS 10.15 beta 5
Ruby 2.6.3
Rails 6 RC 2

>                             Version: freetds v1.1.11
>              freetds.conf directory: /usr/local/etc
>      MS db-lib source compatibility: no
>         Sybase binary compatibility: yes
>                       Thread safety: yes
>                       iconv library: yes
>                         TDS version: 7.3
>                               iODBC: no
>                            unixodbc: yes
>               SSPI "trusted" logins: no
>                            Kerberos: yes
>                             OpenSSL: yes
>                              GnuTLS: no
>                                MARS: yes

> xcode-select version 2368.

> LibreSSL 2.8.3

Any suggestions on environmental factors that I can troubleshoot?

**Comment by shrmnk** [comment] 2019-08-02 14:50
Hey @wpolicarpo so sorry about this - missed the notifications. I've since returned my Mac due to screen issues and am now developing on a windows machine.

**Comment by aditya87** [comment] 2019-12-11 23:05
I am facing this issue, Rails 5.2.3, postgres 12.1, xcode-select 2354, LibreSSL 2.6.5. I am on macOS 10.14.6. The exact error happens when I try to list any record in the console:

```
objc[23784]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called.
objc[23784]: +[__NSPlaceholderDate initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

I recently updated openssl and reinstalled ruby. Reinstalled `xcode-select` to no avail, doing a MacOS update now.

**Comment by aditya87** [comment] 2019-12-12 00:47
Update: downgraded to postgres 9.5 and the error went away.

**Comment by wpolicarpo** [comment] 2019-12-12 10:42
@etcook I've noticed you're running Rails 6. Worth mentioning that the adapter does not support Rails 6 yet and I'm trying to find some time to work on it.

Regarding the original error, the problem might be how `freetds` was compiled not the adapter itself, but I can't reproduce the error myself. Sorry I could not help.

I'm closing this off. If someone finds something related or can write a reproducible script, please advise.

**Closed by wpolicarpo** 2019-12-12 10:42 UTC
