### ISSUE TITLE
Datetime2 column returned as string in ActiveRecord Query even though TinyTDS returns as Time, vers 4.2

### ISSUE THREAD

**Issue by kinnairdclan** [rails-sqlserver/activerecord-sqlserver-adapter#706] opened 2019-09-04 18:48 UTC
We are attempting a transition from a PostgreSQL to MSSQL with existing data. When pulling a Datetime2 field from our Windows SQL Server 2016 system, a Datetime2 column is returned by ActiveRecord as a string instead of the Rails Object ActiveRecord::TimeWithZone. Definitely using tds_version: '7.3' in my database.yml which seems to be a major culprit of similar issues. The interesting thing is that TinyTDS is returning this value as a Time, which seems more accurate and correct. The adapter appears to be casting it to a string:

```
> result = client.execute("USE Mintrak2 SELECT TOP 1 password_created_at FROM users")
 => #<TinyTds::Result:0x00007ff299d928d8 @query_options={:as=>:hash, :symbolize_keys=>false, :cache_rows=>true, :timezone=>:local, :empty_sets=>true}>
> result_hash = result.first
 => {"password_created_at"=>2017-05-17 06:00:00 -0600}
> result_hash.values.first.class
 => Time
> User.first.password_created_at.class
  User Load (16.7ms)  EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
 => String
> User.first.password_created_at
  User Load (13.4ms)  EXEC sp_executesql N'SELECT  [users].* FROM [users]  ORDER BY [users].[id] ASC OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY'
 => "2017-05-17 06:00:00 UTC"
```

I just wanted to know if I was potentially configuring something incorrectly or if this is expected behavior? Thanks in advance.

**Operating System**

Distributor ID: Debian                                                                          
Description:    Debian GNU/Linux 9.9 (stretch)                                                  
Release:        9.9                                                                             
Codename:       stretch                                                                         
Linux stretch-dev-env 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 GNU/Linux

**TinyTDS Version and Information**
2.1.2, could not run ttds-tsql, odd since we're installed and connecting just fine.

**FreeTDS Version**
Compile-time settings (established with the "configure" script)  
Version: freetds v1.1.15             
freetds.conf directory: /usr/local/etc              
MS db-lib source compatibility: no                          
Sybase binary compatibility: no                          
Thread safety: yes                         
iconv library: yes                         
TDS version: 7.3                         
iODBC: no                          
unixodbc: no                          
SSPI "trusted" logins: no                          
Kerberos: no                          
OpenSSL: yes                         
GnuTLS: no                          
MARS: yes               

**Rails**
Ruby: 2.3.8
Rails: 4.2
activerecord-sqlserver-adapter: 4.2.0

**Comment by wpolicarpo** [comment] 2020-05-19 19:24
I ran the test case below and looks like the issue is gone for Rails >= 5.

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  gem "tiny_tds"
  gem "activerecord", "~> 5.0.0"
  gem "activerecord-sqlserver-adapter", "~> 5.0.0"
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter:  "sqlserver",
  timeout:  5000,
  pool:     100,
  encoding: "utf8",
  database: "issues_development",
  username: "rails",
  password: "",
  host:     "localhost",
  port:     1433,
)
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  drop_table :bug_tests rescue nil

  create_table :bug_tests, force: true do |t|
    t.datetime2 :field_at
  end
end

class BugTest < ActiveRecord::Base
end

class TestBugTest < Minitest::Test
  def setup
    @now = Time.now
    @bug_test = BugTest.create!(field_at: @now)
  end

  def test_count
    assert_equal Time, BugTest.first.field_at.class
  end
end
```

Since the Rails team is not actively maintaining Rails 4.2 anymore, I decided to do the same with the adapter so it is possible to give attention to the newer versions.

I am closing this off for now but I would be happy to review a PR backporting the fix to `4-2-stable` branch.

**Closed by wpolicarpo** 2020-05-19 19:24 UTC
Labels: bug, rails-4-2

**Comment by kinnairdclan** [comment] 2020-05-20 16:00
Thanks for the response, much appreciated; looks like an upgrade to 5.0 is the way to go.
