### ISSUE TITLE
After 4.2.8 I have this error: NoMethodError - undefined method `database_prefix_remote_server?'

### ISSUE THREAD

**Issue by ginolon** [rails-sqlserver/activerecord-sqlserver-adapter#450] opened 2016-02-29 16:04 UTC
```
NoMethodError - undefined method `database_prefix_remote_server?' for #<ActiveRecord::ConnectionAdapters::PostgreSQLAdapter:0x007f1ef003ee20>:
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:77:in `visit_Arel_Table'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:601:in `visit_Arel_Nodes_InnerJoin'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:794:in `block in inject_join'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:792:in `inject_join'
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:96:in `visit_Arel_Nodes_JoinSource'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/to_sql.rb:248:in `visit_Arel_Nodes_SelectCore'
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:67:in `block in visit_Arel_Nodes_SelectStatement'
  activerecord-sqlserver-adapter (4.2.8) lib/arel/visitors/sqlserver.rb:66:in `visit_Arel_Nodes_SelectStatement'
  arel (6.0.3) lib/arel/visitors/reduce.rb:13:in `visit'
  arel (6.0.3) lib/arel/visitors/reduce.rb:7:in `accept'
```

**Comment by KDGundermann** [comment] 2016-03-03 17:35
There seems to be some configuration mismatch:

**Comment by ginolon** [comment] 2016-03-03 17:51
The latter.

**Comment by metaskills** [comment] 2016-03-08 01:48
I see you are a) using PostgreSQL adapter in your stack and b) somehow the PG adapter is using the Arel visitor. Can you investigate your setup and find out why?

**Comment by metaskills** [comment] 2016-03-15 00:38
Closing issue.

**Comment by RyanSpittler** [comment] 2016-03-28 16:40
Got this same issue. We use MySql2 for our Rails DB. Here's the error:
```
NoMethodError: undefined method `database_prefix_remote_server?' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x000000065adb00>
from /gems/activerecord-sqlserver-adapter-4.2.8/lib/arel/visitors/sqlserver.rb:77:in `visit_Arel_Table'
from /gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
from /gems/activerecord-sqlserver-adapter-4.2.8/lib/arel/visitors/sqlserver.rb:103:in `visit_Arel_Nodes_OuterJoin'
from /gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:794:in `block in inject_join'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each_with_index'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `inject'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `inject_join'
from /gems/activerecord-sqlserver-adapter-4.2.8/lib/arel/visitors/sqlserver.rb:96:in `visit_Arel_Nodes_JoinSource'
from /gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
from /gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:248:in `visit_Arel_Nodes_SelectCore'
from /gems/activerecord-sqlserver-adapter-4.2.8/lib/arel/visitors/sqlserver.rb:67:in `block in visit_Arel_Nodes_SelectStatement'
from /gems/activerecord-sqlserver-adapter-4.2.8/lib/arel/visitors/sqlserver.rb:66:in `each'
from /gems/activerecord-sqlserver-adapter-4.2.8/lib/arel/visitors/sqlserver.rb:66:in `inject'
```
Happens when we try to perform a join on two tables, both of which should be using the adapter. It works fine when used with `includes` in place of `joins`.
For example, `FirstTable.joins(:second_table)` fails with this error.
`FirstTable.includes(:second_table)` works normally.
It seems to work when you pass the actual name of the table in the `joins` as a string. For example, `FirstTable.joins('second_table')` works. However, you must use the actual name of the table in the SQLServer Database, instead of the name of the relation Model you have given it in Rails.
@ginolon It appears from your errors that you may be trying to perform a similar action with a `joins`. This may help temporarily fix your issue.

**Comment by RyanSpittler** [comment] 2016-03-28 23:06
More info:
Confirmed that this is not an issue with 4.2.6, but IS an issue with 4.2.8 and 4.2.10.
We use two different connections for databases. The main Rails database is using the MySQL2 Adapter, and we are using a read only connection to access data on the SQLServer. We are using the Octoshark gem as a connection manager.
It appears that the connection to the database gets reset in the middle of a `joins` operation. At the time of the error, I assume that it is expecting a SQLServerAdapter connection, but instead it gets the default.
When not using `joins` or `includes`, calls to the SQLServer database function correctly, and data is received normally.

**Comment by RyanSpittler** [comment] 2016-03-28 23:59
It appears to be induced by commit f90848a.

**Comment by metaskills** [comment] 2016-03-29 00:15
Good sleuthing! Do you think the issue is with Octoshark? For example, what if you used the DB to ensure the user could only do reads and a simple gem like Secondbase https://github.com/customink/secondbase Does the issue still happen?

**Comment by RyanSpittler** [comment] 2016-03-29 14:16
I just tried out SecondBase. Unfortunately, the issue still happens. The individual Models work fine when calling things like `TableName.last`. The error occurs when trying to apply a join. It's almost like the Adapter forfeits control or something.
Fortunately, both SecondBase and Octoshark are rather lightweight, so changing between the two is rather simple. I would say that SecondBase seems a bit easier to implement in this case.

**Comment by metaskills** [comment] 2016-03-29 14:19
Thank you so much for trying that! If indeed the issue did come up in f90848a then maybe it is the `visit_Arel_Table` visitor leaking to another adapter's visitor? Perhaps try to `$ bundle open activerecord-sqlserver-adapter` then open the visitor, comment out that method entirely, restart your app and see what happens?

**Comment by RyanSpittler** [comment] 2016-03-29 14:58
Found the right place, and yes, commenting out the `visit_Arel_Table` method seems to allow both the `joins` and the `includes` to function properly. Not sure if that breaks other things.
Btw, I was working with that specific commit, f90848a. I'll test it on 4.2.10 in just a moment.

**Comment by RyanSpittler** [comment] 2016-03-29 15:10
Yup, commenting out that same method in 4.2.10 resolves the `joins` issue.

**Comment by metaskills** [comment] 2016-03-29 15:12
Damn...

**Comment by metaskills** [comment] 2016-03-29 15:14
Damn... so this exposes a weakness in ActiveRecord and I need to ponder if/how we fix it while allowing the work in #426 and #427 to continue cc @jippeholwerda

**Comment by RyanSpittler** [comment] 2016-03-29 15:17
No worries. I'm planning on rolling back to 4.2.6 for now.

**Comment by RyanSpittler** [comment] 2016-03-29 15:21
Could the method just `return` if it doesn't get the Adapter it was expecting? I admit that I'm not knowledgable enough to know what is going on. ',=)

**Comment by jippeholwerda** [comment] 2016-03-29 18:19
Hmm, the combination of the Mysql2Adapter using the SQLServer Arel visitor doesn't seem right to me...

@RyanSpittler Could you perhaps provide a minimal testcase in which the issue can be reproduced?

**Comment by RyanSpittler** [comment] 2016-03-29 20:47
No problem. I just created a new Rails project and generated the error in this way:

1. Created a new Rails project. I used as much of the defaults as possible, so I kept SQLite3 as the database adapter: `rails new AdapterTest`

2. Just to ensure that the database exists and works, I generated a Model: `rails g model Gadget name:string part:string`

3. Applied that table to the database: `rake db:create` and `rake db:migrate`

4. Tested that it worked in `rails console` and that we had a database. We should be good to go.

5. Added the necessary gems for a second SQLServer database. I used SecondBase, just to be safe:
    ```ruby
    gem 'activerecord-sqlserver-adapter'
    gem 'tiny_tds'
    gem 'secondbase'
    ```
6. Bundle.

    > Since the SQLServer already exists, and I'm using read access, I didn't have to create new tables. I just had to reference existing tables. No need to `rake` again.

7. Add the second database to the `database.yml`:
    ```yml
    secondbase:
      development:
        adapter: sqlserver
        username: example
        password: example
        host: example.com
        database: example
    ```

8. Add a couple Models for the tables that are present in the SQLServer database. For example:
    ```ruby
    class Account < SecondBase::Base
      self.table_name = 'acct'
      self.primary_key = 'acct_id'
      has_many :payments, foreign_key: 'acct_id'
    end
    ```
    ```ruby
    class Payment < SecondBase::Base
      self.table_name = 'acct_payment'
      self.primary_key = 'row_id'
      belongs_to :account, foreign_key: 'acct_id'
    end
    ```
    > Obviously, this is example information. Replace it with your actual database table schema.
9. Tested the individual tables. `Account.last` provides an actual row of information, as well as `Payment.last`.

10. Tested a `joins`. `Account.joins(:payments).count` fails (as well as others).

**Comment by RyanSpittler** [comment] 2016-03-29 20:53
Here's the error for the example:
```
irb(main):003:0> Account.joins(:payments).count
NoMethodError: undefined method `database_prefix_remote_server?' for #<ActiveRecord::ConnectionAdapters::SQLite3Adapter:0x007f8fc3351d80>
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-4.2.10/lib/arel/visitors/sqlserver.rb:77:in `visit_Arel_Table'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:601:in `visit_Arel_Nodes_InnerJoin'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:794:in `block in inject_join'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each_with_index'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `each'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `inject'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:792:in `inject_join'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-4.2.10/lib/arel/visitors/sqlserver.rb:96:in `visit_Arel_Nodes_JoinSource'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/reduce.rb:13:in `visit'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/arel-6.0.3/lib/arel/visitors/to_sql.rb:248:in `visit_Arel_Nodes_SelectCore'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-4.2.10/lib/arel/visitors/sqlserver.rb:67:in `block in visit_Arel_Nodes_SelectStatement'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-4.2.10/lib/arel/visitors/sqlserver.rb:66:in `each'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-sqlserver-adapter-4.2.10/lib/arel/visitors/sqlserver.rb:66:in `inject'
... 12 levels...
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/console.rb:9:in `start'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/railties-4.2.4/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:274:in `require'
	from /Users/ryanspittler/dev/AdapterTest/bin/rails:9:in `<top (required)>'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:268:in `load'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/ryanspittler/.rbenv/versions/2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'irb(main):004:0> exit
```

**Comment by jippeholwerda** [comment] 2016-03-30 07:02
Cool, nice example! I'll see if I can have a look at it today.

**Comment by jippeholwerda** [comment] 2016-04-06 10:56
So I finally had some time to dive into the issue and was able to trace it back to ActiveRecord.

When ActiveRecord is constructing the objects used in the join, it is constructing a new Arel table object for the joining model. When creating an Arel table object, an engine can be provided. The engine is used for connection pooling, quoting, type casting, etc, and is adapter specific. However, if the engine is not provided, the default `Table.engine` will be used. In this case, it is `ActiveRecord::Base`, which uses the SQLite3 adapter. So I noticed that ActiveRecord creates an alias for the joining model in the method `aliased_table_for` in `associations/alias_tracker.rb`, and creating a new Arel table object in the process without providing an engine, leading to the problem at hand.

In my opinion, this is wrong. The information which engine to use is available and should be used when creating the Arel table, instead of relying on the default engine.

So in order to fix it we could consider creating a pull request for ActiveRecord in which the engine is provided when constructing a new Arel table object.

In the meantime, we could temporarily fix it in the sqlserver adapter by checking if the connection is the adapter we're expecting (or if the `database_prefix_remote_server` exists).

Also, I'm not sure yet how Rails 5 will handle this. It seems the engine has been removed from the Arel table and is now provided when calling `to_sql` and `where_sql` (https://github.com/rails/arel/commit/98fc25991137ee09b6800578117f8c1c322680f2).

@metaskills What do you think?

**Comment by metaskills** [comment] 2016-04-06 11:10
Brilliant. I think a fix to 4-2-stable makes perfect sense and we might be able to get @sgrif to help with that. In doing so, we can ask Rails core team what they think about the issue as it relates to Rails 5 too.

I am also open to a patch in the 4-2-stable/master branches of the adapter too.

**Comment by sgrif** [comment] 2016-04-06 11:40
I can do a patch upstream. Can you write up a reproduction script using the Rails template?

**Comment by jippeholwerda** [comment] 2016-04-06 12:52
`gem "activerecord-sqlserver-adapter"
gem "tiny_tds"
gem "secondbase"

file "config/database.yml", <<-CODE
default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

secondbase:
  development:
    adapter: sqlserver
    username: <username>
    password: <password>
    host: <server>
    database: <database>
CODE

generate("second_base:migration", "create_account", "number:string")
generate("second_base:migration", "create_payment", "amount:string", "account:references")

file "app/models/account.rb", <<-CODE
class Account < SecondBase::Base
  has_many :payments
end
CODE

file "app/models/payment.rb", <<-CODE
class Payment < SecondBase::Base
  belongs_to :account
end
CODE

rake "db:migrate"
`

You will need access to a SQL Server database. Reproduce by running `Account.joins(:payments).count` in Rails console.

**Closed** 2016-04-24 01:03 UTC

**Comment by metaskills** [comment] 2016-04-24 02:29
I will have v4.2.11 out this weekend with this fix in it.

**Comment by RyanSpittler** [comment] 2016-04-25 13:35
@metaskills @jippeholwerda Thanks, guys!
