### ISSUE TITLE
Error during conversion from varchar to samlldatetime.

### ISSUE THREAD

**Issue by ginolon** [rails-sqlserver/activerecord-sqlserver-adapter#448] opened 2016-02-29 08:36 UTC
I need help with this:

tha same variable `@myDate = DateTime.now`

(or also `DateTime.now.strftime('%a %b %d %H:%M:%S %Z %Y'`, or also `DateTime.now.to_time`)

is causing me error in query.

`Error during conversion from varchar to samlldatetime.`

My query is for two different tables:

The first is ok, but Date is not PRIMARY KEY and NULL values are accepted.

The second, where is the error, IS **PRIMARY KEY** and **NULL VALUES ARE NOT ACCEPTED**.

I'm using:

```ruby
gem 'tiny_tds', '~> 0.9.5.rc.3'
gem 'activerecord-sqlserver-adapter'
```

or also

```ruby 
gem 'tiny_tds', '~> 0.7.0'
gem 'activerecord-sqlserver-adapter'
```

Rails 4.2.5 and SQL Server 2012.

**Comment by ginolon** [comment] 2016-02-29 09:49
I the variable

`@myDate` is: `DateTime.now` and then `2016-02-29T09:45:01+00:00`

in my first table everything is OK. No problem.

In my second table I have the error.

If I change the big query from this:

`EXEC sp_executesql N'INSERT INTO ... bla bla bla ... SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident', N'@0 smalldatetime,  ... bla bla bla ... ', @0 = '02-29-2016 09:45:01.855', ... bla bla bla ...`

to 

`EXEC sp_executesql N'INSERT INTO ... bla bla bla ... SELECT CAST(SCOPE_IDENTITY() AS bigint) AS Ident', N'@0 smalldatetime,  ... bla bla bla ... ', @0 = '2016-29-02 09:45:01.855', ... bla bla bla ...`

the query is accepted from my sql server!

**How to fix this?**

**Comment by metaskills** [comment] 2016-02-29 12:04
Try not using `DateTime` but `Time.current` instead. The `DateTime` class in Ruby is kind of dead and we recommend using just `Date` or `Time`. Do not format the string either. Let ActiveRecord do that according to the rules as needed for your DB.

**Comment by ginolon** [comment] 2016-02-29 12:07
The problem is the same.

**Comment by metaskills** [comment] 2016-02-29 12:13
I just pushed v4.2.8 of the adapter, can you try that out?

**Comment by ginolon** [comment] 2016-02-29 12:15
With **4.2.8** the same error: 

`Error converting data type from nvarchar to smalldatetime`

but now it is **n**varchar.

How to fix?

If I modify the query

from: `02-29-2016 12:11:16.851`

to: `2016-29-02 12:11:16.85196`

the problem gone away.

**Comment by metaskills** [comment] 2016-02-29 12:18
I have a hunch what this might be, just working thru a process. Can you show me the full output of this from your console.

```ruby
Date::DATE_FORMATS.select { |k,_v| k.to_s =~ /sqlserver/ }
```

**Comment by ginolon** [comment] 2016-02-29 12:56
On my Rails c:

`irb(main):001:0> Date::DATE_FORMATS.select { |k,_v| k.to_s =~ /sqlserver/ }
=> {}`

Now I tried on SQL Server in English and it works.

On France, Italian and Czech it doesn't. The problem of date. Why?

**Comment by metaskills** [comment] 2016-02-29 13:36
Hmmm... show me all of `Date::DATE_FORMATS` please.

**Comment by ginolon** [comment] 2016-02-29 13:44
Ok, here it is:

```
{:short=>"%e %b", :long=>"%B %e, %Y", :db=>"%Y-%m-%d", :number=>"%Y%m%d", :long_ordinal=>#<Proc:0x007f68b81dc518@/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/date/conversions.rb:12 (lambda)>, :rfc822=>"%e %b %Y", :iso8601=>#<Proc:0x007f68b81dc4a0@/home/vagrant/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/activesupport-4.2.5.1/lib/active_support/core_ext/date/conversions.rb:17 (lambda)>}
```

**Comment by metaskills** [comment] 2016-02-29 13:51
When you boot the Rails console, make sure to load the database first. You can do a model find, anything that instantiates the connection. For example `ActiveRecord::Base.connection` would work. Once you do that, you should see a few `_sqlserver_*` formats in both:

* Date::DATE_FORMATS
* Time::DATE_FORMATS

You can see these instantiated here:

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver_adapter.rb#L60

https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/blob/master/lib/active_record/connection_adapters/sqlserver_adapter.rb#L382-L394

Once you hit the connection. Do you have date/time formats set? What I think is happening is the forms are either not being set, or they are not being set correctly for your language in the `user_options_dateformat` helper method. See where I am going?

**Comment by ginolon** [comment] 2016-02-29 14:14
Ok, not it is:

`=> {:_sqlserver_dateformat=>"%m-%d-%Y"}`

**Comment by metaskills** [comment] 2016-02-29 14:24
Well, these come from the user options. We have a few options. You can help the adapter by proposing a stronger `user_options` and `user_options_dateformat` method implementation. Find these in our database_statments.rb file. Note how we reflect on the current language in the Azure implementation. Maybe there is a better way we can do this for non-Azure?

**Comment by metaskills** [comment] 2016-02-29 14:25
Like maybe we could use the same SQL we do for Azure? Can you test that?

**Comment by ginolon** [comment] 2016-02-29 14:34
Can I create in my **config/locales/fr.yml** my own *format*?

Like:

`db: "%Y-%d-%m"`?

**Comment by metaskills** [comment] 2016-02-29 14:35
I am more interested in solving this at the adapter level so others do not have issues.

**Comment by ginolon** [comment] 2016-02-29 15:23
It doesn't work neither with

`db: "%Y-%d-%m %H:%M:%S"` cin **fr.yml** or **it.yml**.

When I try on SQL Server in english it works without problems.

How to fix?

**Comment by metaskills** [comment] 2016-04-24 22:37
I tried to reproduce this by charing my SQL Server database to French via:

```sql
USE [activerecord_unittest];
EXEC sp_configure 'default language', 2;
RECONFIGURE;
```

But that nor changing my user or even SET'ing the language post connect worked. It might be that my developer edition does not support that feature and locks down the language/format to `mdy` for me. Since I can not get that changed to research a new way other than dbcc useroptions. The only way to fix this is to use our [Configure Connection & App Name](https://github.com/rails-sqlserver/activerecord-sqlserver-adapter#configure-connection--app-name) feature. Please read that document link and I suggest doing this in that method.

```ruby
raw_connection_do "SET DATEFORMAT ymd"
```

Hope that helps. Closing this issue.

**Closed by metaskills** 2016-04-24 22:37 UTC
Labels: 4-2-stable
