### ISSUE TITLE
Rails 5.2

### ISSUE THREAD

**Issue by krushi123** [rails-sqlserver/activerecord-sqlserver-adapter#636] opened 2018-01-24 05:37 UTC
Hi, When I add the Gem into a rails app with 5.2.0.beta - It is raising an error. Can not think of any breaking changes between 5.1 and 5.2 regarding ActiveRecord. Can you please suggest how to make it work?

**Comment by metaskills** [comment] 2018-01-24 15:19
No work has been done for 5.2 yet. It'll be a few weeks. Sorry.

**Comment by juice** [comment] 2018-03-29 07:20
Any updates? Rails 5.2 is now a rc2. Time to update the Adapter so we can use Rails 5.2 when it is released. Or even better test our Apps before it is released.

**Comment by juice** [comment] 2018-04-10 05:44
Rails 5.2 is released, any idea when we will see a working version?

**Comment by benbarber** [comment] 2018-04-23 14:37
Any update on 5.2 support, has any progress been made?

**Comment by spacerobotTR** [comment] 2018-05-07 17:56
+1 to this. Would love to fire up a new 5.2 project with SQL server.

**Comment by brentdodell** [comment] 2018-05-09 14:54
+1 Trying to update to 5.2 now.

**Comment by codiemullins** [comment] 2018-05-18 14:05
@metaskills Are there known issues that prevent the gem from being compatible with Rails 5.2? 

I'm working to upgrade an enterprise application and would like to take it to 5.2, but this is the only critical gem that doesn't support it.

I'm happy to assist in testing its compatibility with 5.2, but unsure where to start. Thank you for the great work!

**Comment by maurosbu** [comment] 2018-05-18 15:02
+1 for Rails 5.2 support. 
I'm upgrading an _ecosystem_ of apps (15 apps) to Rails 5.2 and one of those is using your gem.
Many thanks for your great work!!

Mauro

**Comment by brandoncordell** [comment] 2018-06-01 14:46
@codiemullins I don't know if you've made any progress but the problem is that `alias_method_chain` has been removed from Rails completely (deprecated in 5.1). It's recommended that people use [Module#prepend](https://ruby-doc.org/core-2.2.0/Module.html#method-i-prepend) instead.

**Comment by BenMcH** [comment] 2018-06-20 18:50
@metaskills Do you have any updates on Rails 5.2 compatibility? I am currently in the process of updating an old Rails app and this is the only gem that is stopping me from doing that.

**Comment by BenMcH** [comment] 2018-06-21 15:00
Thanks for the update! If I get a chance, I'll try to pull down the code and start looking at it, but I'm not sure how much help I would be. If I'm successful, I'll send a PR!

**Comment by matthewdunbar** [comment] 2018-07-05 17:59
I've made some progress on upgrading to Rails 5.2. I currently only have about 40 tests failing, though it seems to mostly work in use in a real application. Here's my fork, changes are on master: https://github.com/matthewdunbar/activerecord-sqlserver-adapter

**Comment by wpolicarpo** [comment] 2018-07-09 12:19
@matthewdunbar don't you want to open a PR here so we can help you? I've made some progress as well, but noticed we have more or less the same changes. It might be a good idea we concentrate our efforts so we don't duplicate work.

**Comment by matthewdunbar** [comment] 2018-07-09 13:12
@wpolicarpo It looks like your changes weren't committed yet last time I looked through the network tab, but I like what you have. Its a little more succinct than what I came up with. I did open a PR on this project late last week.

**Comment by wpolicarpo** [comment] 2018-07-09 14:11
@matthewdunbar Cool, I haven't seen you PR before, sorry. I pulled some of your changes into my branch and this is what I have so far:

```
Finished in 396.715748s, 13.4857 runs/s, 39.9127 assertions/s.

5350 runs, 15834 assertions, 28 failures, 60 errors, 5 skips
```

I'll try to make a list on your PR so we can track our progress there if you don't mind.

**Comment by matthewdunbar** [comment] 2018-07-09 14:59
@wpolicarpo Awesome! Thanks for the feedback on this.

**Comment by UnConundrum** [comment] 2018-07-24 18:57
Hi.  Are there any updates?

**Comment by spacerobotTR** [comment] 2018-08-22 18:39
Any news on this?

**Comment by metaskills** [comment] 2018-08-22 18:58
See here right? https://github.com/rails-sqlserver/activerecord-sqlserver-adapter/pull/653#issuecomment-415142254

**Comment by spacerobotTR** [comment] 2018-08-22 19:05
Thank you!

**Comment by thomasfedb** [comment] 2018-09-16 13:51
Signed up as a $50/mo backer, given that this gem is important for my freelance work. Hope that helps a little to keep things going.

**Comment by gr8bit** [comment] 2018-11-13 13:00
@thomasfedb We're 3 patr(e)ons already! Far from the $3k target though :( If anyone else loves this gem and wants to join us: https://www.patreon.com/metaskills/overview :)

**Comment by rhuanbarreto** [comment] 2018-12-03 15:11
+1 on this. Important to update the gem!

**Comment by thomasfedb** [comment] 2018-12-03 16:45
@wpolicarpo to clarify, using the master branch with a Rails 5.2 project?

**Comment by juice** [comment] 2018-12-03 17:09
We are using the master branch for a few weeks now on some smaller projects but in our production system. We want to use it in our biggest Project, but we cannot deploy without working tests. It looks like applying  fixtures in tests is not working.

**Comment by wpolicarpo** [comment] 2018-12-03 17:19
@thomasfedb 

Exactly, Rails 5.2.

@juice 

Could you tell us what is not working for you? Can you leave a comment in #662 and maybe I can help you?

**Comment by tommyalvarez** [comment] 2018-12-17 13:34
@wpolicarpo what's the status on this? Do you know by chance an approximate day of release for 5.2 ?

**Comment by wpolicarpo** [comment] 2018-12-17 13:53
@tommyalvarez nothing changed since my last comment and only @metaskills can answer you on the releases matter.

**Comment by metaskills** [comment] 2018-12-17 14:01
@wpolicarpo I have added you as a collaborator to these repos. Feel free to work with others and help drives this to our master branch. I can help publish gems when needed and we can go from there. Sound good?

**Comment by tommyalvarez** [comment] 2018-12-17 14:04
@wpolicarpo understood. Using the master branch will work with 5.2 with no issues for the time being ? I have a production app, but it's not that serious, it's only for querying info in the background...

**Comment by metaskills** [comment] 2018-12-17 14:08
Just a reminder that pushing code to the master branch of this repo means it should have a high standard of QA. For example a checklist of things would be a) a public pull request, even if short lived b) tests passing.

**Comment by wpolicarpo** [comment] 2018-12-17 14:44
@tommyalvarez 

I have a reasonably big application running `master` branch and didn't have any issues so far.

@metaskills 

Thanks for that. I will try to fix `master` tests so we can release at least an alpha version in the next days.

**Comment by tommyalvarez** [comment] 2018-12-22 17:11
@wpolicarpo i found a bug i think with 5.2. Even after specifying  in an initializer:

`ActiveRecord::ConnectionAdapters::SQLServerAdapter.lowercase_schema_reflection = true
`
When doing a join between two tables like `Foo.joins(:bar)`, it appends an _order by_ to the query but without lower casing the attributes. so an invalid tiny_tds exception is thrown saying column attribute_not_lowercased does not exist...

**Comment by jasonperrone** [comment] 2019-01-07 23:50
Can somebody recommend another SQL Server adapter for Ruby that does work with 5.2?

**Comment by wpolicarpo** [comment] 2019-01-08 00:15
@tommyalvarez since ActiveRecord doesn't support composite PKs by default, I don't think we should treat this here. It's more likely that you have to check with that gem to see what they can do in this case.

**Comment by metaskills** [comment] 2019-01-08 00:55
> I don't think we should treat this here. It's more likely that you have to check with that gem to see what they can do in this case.

Agreed. I've always taken that perspective. Easier for them to support patches on each adapter as part of their extension gem.

**Comment by DrCool2** [comment] 2019-01-09 16:48
Looking forward to using Rails 5.2 and SQLServer. Status Update?

**Comment by jasonperrone** [comment] 2019-01-16 18:40
DrCool2, if it helps, the master branch works with 5.2, so if you define the Gemfile like this, you'll be ok:
gem 'activerecord-sqlserver-adapter', git: 'https://github.com/rails-sqlserver/activerecord-sqlserver-adapter.git', branch: 'master'

**Comment by wpolicarpo** [comment] 2019-01-24 12:18
@metaskills I have fixed all issues for 5.2 changes and all tests are passing again. Do you think we can release something soon?

**Comment by thomasfedb** [comment] 2019-01-25 02:07
@jbwl can you open an issue with an example so I can attempt a reproduction?

**Comment by juice** [comment] 2019-01-25 08:43
@wpolicarpo I tried the newest code from master.

We have this option set in our adapter model


```
   (0.1ms)  BEGIN
  Fixture Delete (1.6ms)  DELETE FROM [StoragePolicy]; SELECT @@ROWCOUNT AS AffectedRows
  SQL (0.6ms)  SET IDENTITY_INSERT [StoragePolicy] ON
  Fixture Insert (1.6ms)  INSERT INTO [StoragePolicy] ([sp_ID], [sp_sl_ID], [sp_c_ID], [sp_Name], [sp_Description], [sp_CopyToArchive], [sp_CopyToArchiveAfterDays], [sp_RemoveFromWorkspace], [sp_RemoveFromWorkspaceAfterDays], [sp_ShortName], [sp_IsExplicitContentPolicy]) VALUES (1, 1, 1, N'Test', N'Test Test Test', 1, 20, 1, 20, N'test', 0)
  SQL (0.5ms)  SET IDENTITY_INSERT [StoragePolicy] OFF


TypeError: can't quote ActiveRecord::ConnectionAdapters::SQLServer::Type::Data

ActiveRecord::StatementInvalid:         ActiveRecord::StatementInvalid: TinyTds::Error: Incorrect syntax near '`'.: INSERT INTO `StoragePolicy` (`sp_ID`, `sp_sl_ID`, `sp_c_ID`, `sp_Name`, `sp_Description`, `sp_CopyToArchive`, `sp_CopyToArchiveAfterDays`, `sp_RemoveFromWorkspace`, `sp_RemoveFromWorkspaceAfterDays`, `sp_ShortName`, `sp_IsExplicitContentPolicy`) VALUES (1, 1, 1, 'Test', 'Test Test Test', TRUE, 20, TRUE, 20, 'test', FALSE), (2, 1, 1, 'Test', 'Test Test Test', TRUE, 20, TRUE, 20, 'test', FALSE)


SQL (0.6ms)  BEGIN TRANSACTION
  Fixtures Load (1.0ms)  DELETE FROM [StoragePolicy]
  Fixtures Load (1.3ms)  INSERT INTO `StoragePolicy` (`sp_ID`, `sp_sl_ID`, `sp_c_ID`, `sp_Name`, `sp_Description`, `sp_CopyToArchive`, `sp_CopyToArchiveAfterDays`, `sp_RemoveFromWorkspace`, `sp_RemoveFromWorkspaceAfterDays`, `sp_ShortName`, `sp_IsExplicitContentPolicy`) VALUES (1, 1, 1, 'Test', 'Test Test Test', TRUE, 20, TRUE, 20, 'test', FALSE), (2, 1, 1, 'Test', 'Test Test Test', TRUE, 20, TRUE, 20, 'test', FALSE)
  SQL (0.7ms)  IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION
   (3.2ms)  SELECT s.name, o.name
FROM sys.foreign_keys i
INNER JOIN sys.objects o ON i.parent_object_id = o.OBJECT_ID
INNER JOIN sys.schemas s ON o.schema_id = s.schema_id

```

**Comment by wpolicarpo** [comment] 2019-01-25 17:10
@juice can you open an issue describing the columns types of `StoragePolicy` with a reproducible script or error backtrace at least?

**Comment by juice** [comment] 2019-01-28 08:01
@wpolicarpo I created a rails project with one table and one field. 

https://github.com/juice/mssql-test

execute: rails test

I hope you can help use with this one.

**Comment by thomasfedb** [comment] 2019-01-30 07:50
Hey @wpolicarpo, would be keen to know where things are up to. Can you update us?

**Comment by wpolicarpo** [comment] 2019-01-30 14:57
@thomasfedb I am waiting for @metaskills to release a new version. For now, people can point their projects to `master` and give feedback. There isn't much I can do.

**Comment by opensas** [comment] 2019-02-12 06:51
Gee I hope you can get thru it pretty soon, I've just realized that latest version of redmine is waiting for rails 5.2 support too...

> Redmine 4.0 does not support SQL Server as of December 2018 because a dependent library activerecord-sqlserver-adapter does not support Rails 5.2 yet.

see: http://www.redmine.org/projects/redmine/wiki/RedmineInstall#Supported-database-back-ends

**Comment by metaskills** [comment] 2019-02-12 09:41
@wpolicarpo Added you to ruby gems as a gem owner to help.

**Closed** 2019-02-12 21:38 UTC
Labels: Rails 5.2

**Comment by wpolicarpo** [comment] 2019-02-12 22:00
Thanks, @metaskills!

I have released `5.2.0.rc1` and will wait a few days to release the final `5.2.0`. Worth mentioning that I've been using code in `master` for a few weeks without any issues.

For those waiting for the final `5.2.0` version, please install `5.2.0.rc1` and let us know about any issues you find.

**Comment by gr8bit** [comment] 2019-02-12 22:01
I upgraded from 5.1.6 to master an hour ago, will update to 5.2.0.rc1 right now :) Thank you!

**Comment by net1957** [comment] 2019-03-03 19:07
updated from rails 5.1.6 to rails 5.2.2 and activerecord-sqlserver-adapter 5.2.0.rc1 without issue.
I'm on w10 for test and DB is ms*sql 2014
ruby 2.5.3p105 (2018-10-18 revision 65156) [x64-mingw32]

Thanks!

**Comment by wpolicarpo** [comment] 2019-03-19 22:19
Final 5.2.0 was released.

**Comment by dwood-somniainc** [comment] 2019-10-23 13:14
The gem no longer works for ruby on rails 6.0. I get

```
"Bundler could not find compatible versions for gem "activerecord":
In Gemfile:
 activerecord-sqlserver-adapter was resolved to 5.2.0, which depends on activerecord (~> 5.2.0)
```

**Comment by gr8bit** [comment] 2019-10-23 13:34
@dwood-somniainc it hasn't been tested with 6.0 yet and is always pinned to a major Rails version. Just like this issue was opened, we need a Rails 6.0 issue and somebody to issue some tests on it *nudge, nudge* ;)

**Comment by soosann** [comment] 2020-03-13 05:02
While installing apartment ...this error occurs
The adapter `sqlserver_adapter` is not yet supported (RuntimeError)......
...is it not still supported??
