### ISSUE TITLE
ActiveRecord::Base doesn't belong in a hierarchy descending from ActiveRecord by using a UNION

### ISSUE THREAD

**Issue by cmierich** [rails-sqlserver/activerecord-sqlserver-adapter#665] opened 2018-11-27 08:24 UTC
Hi,

we have an application running with a MS SQL 2014 and:
-  Rails 4.2.10.0  
-  activerecord-sqlserver-adapter v4.2.18

Lately we needed a union over two queries.

By doing so, we got the following error: 

```bash
TestBugUserTest#test_union:
ActiveRecord::ActiveRecordError: ActiveRecord::Base doesn't belong in a hierarchy descending from ActiveRecord
....
```
If you run the UNION query as SQL directly on the MS SQL 2014 database it works.

Running the ruby code below with the hack the union works also:

```bash
export WITH_HACK=YES  && ruby ./ruby_file.rb
```

Running the ruby code below without hack you get the error message mentioned above:

```bash
export WITH_HACK=NO  && ruby ./ruby_file.rb
```

```ruby
ENV["DATABASE_NAME"] = 'REPLACE_WITH_DATABASENAME'
ENV["DATABASE_USERNAME"] = 'REPLACE_WITH_USERNAME'
ENV["DATABASE_PASSWORD"] = 'RPLACE_WITH_PASSWORD'
ENV["DATABASE_HOST"] = 'REPLACE_WITH_HOST'
ENV["DATABASE_PORT"] = '1433'


begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end


gemfile(true) do
  source "https://rubygems.org"

  ruby '2.5.3'

  gem 'rails', '= 4.2.10.0'
  gem 'tiny_tds'
  gem 'activerecord-sqlserver-adapter', '~> 4.2', '>= 4.2.18'
end

require "active_record"
require "minitest/autorun"
require "logger"

ActiveRecord::Base.establish_connection(
  adapter: "sqlserver",
  reconnect: false,
  timeout: 20000,
  pool: 100,
  encoding: "utf8",
  database: ENV["DATABASE_NAME"],
  username: ENV["DATABASE_USERNAME"],
  password: ENV["DATABASE_PASSWORD"],
  host: ENV["DATABASE_HOST"],
  port: ENV["DATABASE_PORT"]
  )

ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Schema.define do
  drop_table :bug_test_users rescue nil
  create_table :bug_test_users, force: true do |t|
    t.string :name
    t.boolean :admin
    t.boolean :manager
    t.timestamps
  end
end

class BugTestUser < ActiveRecord::Base

  def self.retrieve_union_users
    query_1 = BugTestUser.where(admin: true)
    query_2 = BugTestUser.where(manager: true)

    BugTestUser.from("((#{query_1.to_sql}) UNION (#{query_2.to_sql})) AS bug_test_users")
  end
end


class TestBugUserTest < Minitest::Test
  def setup
  end

  def teardown
    ActiveRecord::Schema.define do
      drop_table :bug_test_users
    end
  rescue
  end

  def test_union
    user1 = BugTestUser.create(name: 'User1', admin: true)
    user2 = BugTestUser.create(name: 'User2', manager: true)

    puts '######################'
    puts BugTestUser.retrieve_union_users.to_sql
    puts '######################'

    result =  BugTestUser.retrieve_union_users

    assert_equal(2, result.size)
    assert_equal('User1', result.first.name)
  end
end

module Arel
  module Visitors
    class SQLServer < Arel::Visitors::ToSql

      # Patch from  activerecord-sqlserver-adapter-4.2.18/lib/arel/visitors/sqlserver.rb
      def primary_Key_From_Table(t)

        # dirty hack just to explain the code example
        return 'id' if ENV["WITH_HACK"] == 'YES'

        # Original Code
        return unless t
        return t.primary_key if t.primary_key
        if engine_pk = t.engine.primary_key
          pk = t.engine.arel_table[engine_pk]
          return pk if pk
        end
        pk = t.engine.connection.schema_cache.primary_keys(t.engine.table_name)
        return pk if pk
        column_name = t.engine.columns.first.try(:name)
        column_name ? t[column_name] : nil
      end
    end
  end
end

```

**Comment by thomasfedb** [comment] 2018-12-03 16:31
@cmierich what is the difference between `BugTestUser.retrieve_union_users.to_sql` with and without the hack? What's `primary_Key_From_Table` returning without the hack?

**Comment by cmierich** [comment] 2018-12-04 07:16
@thomasfedb  

Without the hack I get the error message: 
```bash
TestBugUserTest#test_union:
ActiveRecord::ActiveRecordError: ActiveRecord::Base doesn't belong in a hierarchy descending from ActiveRecord
....
```
like I wrote in my post above. This error is raised when the ruby interpreter calls 't.engine.primary_key'  in the original code.

With the hack I get no error message. I return the primary key ('id') through the hack. 
The hack just illustrates where in my opinion the problem could be.

If you have a MSSQL database you could run the code above and see it for yourself.

**Comment by thomasfedb** [comment] 2018-12-04 07:32
Would be good to know more about how/where the original errors out. Very happy to review a PR if you think you can patch it.

**Comment by cmierich** [comment] 2018-12-04 07:52
@thomasfedb
I could send you the complete stack trace. But in my opinion for research it is better you just run the code above.

**Comment by thomasfedb** [comment] 2018-12-04 08:33
Feel free to post the trace. I don't deal with databases with composite keys, so don't have a need to solve this issue personally. Just trying to help if you wanted to submit A PR.

**Comment by thomasfedb** [comment] 2018-12-04 08:34
Fell free to post the trace. I haven't encountered this issue to in my applications, so just trying to help you submit a PR if you wanted to get this fixed.

**Comment by cmierich** [comment] 2018-12-04 08:39
@thomasfedb 

```bash
  1) Error:
TestBugUserTest#test_union:
ActiveRecord::ActiveRecordError: ActiveRecord::Base doesn't belong in a hierarchy descending from ActiveRecord
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/inheritance.rb:102:in `base_class'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/primary_key.rb:84:in `reset_primary_key'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/attribute_methods/primary_key.rb:73:in `primary_key'
    ./rails_single_file.rb:106:in `primary_Key_From_Table'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-sqlserver-adapter-4.2.18/lib/arel/visitors/sqlserver.rb:161:in `make_Fetch_Possible_And_Deterministic'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-sqlserver-adapter-4.2.18/lib/arel/visitors/sqlserver.rb:123:in `visit_Orders_And_Let_Fetch_Happen'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-sqlserver-adapter-4.2.18/lib/arel/visitors/sqlserver.rb:69:in `visit_Arel_Nodes_SelectStatement'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/arel-6.0.4/lib/arel/visitors/reduce.rb:13:in `visit'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/arel-6.0.4/lib/arel/visitors/reduce.rb:7:in `accept'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:12:in `to_sql'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/querying.rb:39:in `find_by_sql'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation.rb:639:in `exec_queries'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation.rb:515:in `load'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation.rb:243:in `to_a'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/finder_methods.rb:500:in `find_nth_with_limit'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/finder_methods.rb:484:in `find_nth'
    /Users/crimi/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/activerecord-4.2.10/lib/active_record/relation/finder_methods.rb:127:in `first'
    ./rails_single_file.rb:88:in `test_union'
```

**Comment by wpolicarpo** [comment] 2020-05-19 18:40
I ran the (excellent) test case against master and looks like the issue is gone there.

Since the Rails team is not actively maintaining Rails 4.2 anymore, I decided to do the same with the adapter so it is possible to give attention to the newer versions.

I am closing this off for now but I would be happy to review a PR backporting the fix to `4-2-stable` branch.

**Closed by wpolicarpo** 2020-05-19 18:40 UTC
Labels: bug, rails-4-2
